from enum import Enum


class AdminRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    CONTENT_ADMIN = "CONTENT_ADMIN"
    MOCKTEST_ADMIN = "MOCKTEST_ADMIN"
    ANALYTICS_ADMIN = "ANALYTICS_ADMIN"
    SUPPORT_ADMIN = "SUPPORT_ADMIN"
